#Change Content
- name: Change content 
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: copy content
      replace:
       path: /var/www/cgi-bin/mycmd.cgi
       regexp: "Address"
       replace: "IP Address"
    - name: copy content
      replace:
       path: /var/www/cgi-bin/mycmd.cgi
       regexp: "ip addr" 
       replace: "ifconfig"
