#Change Content
- name: Change content 
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: copy content
      replace:
       path: /var/tmp/index.html
       regexp: "This is my Web Server"
       replace: "This is my WEB SERVER"
