---
- name: "Generate Web-Visible Server Health Report"
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
  
    - name: ensure apache is at the latest version
      ansible.builtin.dnf:
        name: httpd
        state: latest
    - name: ensure apache is starting
      service:
        name: httpd
        state: started
  
    - name: "Ensure target directory /var/www/html exists"
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'

    # --- Data Collection Tasks ---
    - name: "Get CPU Load Average"
      ansible.builtin.command: cat /proc/loadavg
      register: cpu_load
      changed_when: false

    - name: "Get Memory Usage (in MB)"
      ansible.builtin.command: free -m
      register: memory_usage
      changed_when: false

    - name: "Get Disk Space Usage"
      ansible.builtin.command: df -h /
      register: disk_usage
      changed_when: false

    - name: "Get System Uptime"
      ansible.builtin.command: uptime -p
      register: system_uptime
      changed_when: false

    # *** THIS LINE IS NOW CORRECTED WITH QUOTES ***
    - name: "Check Status of Critical Service (Example: SSHD)"
      ansible.builtin.service:
        name: sshd
        state: started
      register: ssh_status
      ignore_errors: true 

    # --- Report Generation Task ---
    - name: "Render Jinja2 template and place as index.html"
      ansible.builtin.template:
        src: report.j2
        dest: /var/www/html/index.html
        owner: root 
        group: root
        mode: '0644'
      notify: Reload Web Server

  handlers:
    - name: "Reload Web Server"
      ansible.builtin.service:
        name: httpd
        state: reloaded
      listen: "Reload Web Server" 
      ignore_errors: true
