- name: Add User
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Add new user
      ansible.builtin.user:
        name: james, bob, kevin
        shell: /bin/bash
        state: present
      
