- hosts: all
  become: yes
  become_user: root
  vars:
    users_to_add:
      - name: Donna
        shell: /bin/bash
      - name: Mat
        shell: /bin/bash
  tasks:
    - name: Create multiple users
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: "{{ item.shell }}"
        state: present
      with_items: "{{ users_to_add }}"
