       - hosts: all
          vars:
            users_to_add:
              - name: James
                shell: /bin/bash
              - name: Bob
                shell: /bin/bash
              - name: Kevin
                shell: /bin/bash 
          tasks:
            - name: Create multiple users
              ansible.builtin.user:
                name: "{{ item.name }}"
                shell: "{{ item.shell }}"
                state: present
              with_items: "{{ users_to_add }}"
