---
- name: Apply all system updates and reboot if necessary
  hosts: rhel_servers  # Change this to your target group in the inventory
  become: yes          # Use privilege escalation (e.g., sudo)

  tasks:
    - name: Ensure DNF is installed and updated on RHEL 8/9+
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_distribution_major_version | int >= 8
      register: dnf_result

    - name: Ensure YUM is installed and updated on RHEL 7
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_distribution_major_version | int < 8
      register: yum_result

    - name: Determine if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_file

    - name: Reboot the server if the reboot-required file exists or updates were applied
      ansible.builtin.reboot:
        reboot_timeout: 600 # Wait up to 10 minutes for the server to come back
        connect_timeout: 30
      when: reboot_file.stat.exists or dnf_result is changed or yum_result is changed

    - name: Verify system is up and reachable after reboot
      ansible.builtin.wait_for_connection:
        timeout: 300
        delay: 5
      when: reboot_file.stat.exists or dnf_result is changed or yum_result is changed
