- name: Remove User 
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Remove the user 'james'
      ansible.builtin.user:
        name: james
        state: absent
        remove: yes
