#My Apache webserver
- name: remove apache
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: ensure apache is removed
      ansible.builtin.dnf:
        name: httpd
        state: absent
