---
- name: Update system
  hosts: all
  become: yes
  strategy: debug
  - name: Update subset of packages.
      yum:
      name: "{{ item }}"
      state: latest
    with_items:
    - {{ installed_packages | intersect(packages_to_update) }}
